baseURL = "https://Lorpavesby.github.io/"
languageCode = "en-us"
title = "Lorpaves"
theme = "simple-style"
subtitle = "我想知道上帝的思想，其他都是细节。"
githubUrl = "https://github.com/Lorpavesby/Lorpaves.github.io/"
author = "Lorpaves"

